<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>relayout</AssemblyName>
    <RootNamespace>Relayout</RootNamespace>
    <!-- Allows compiling (not running) on non-Windows machines. -->
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <!-- The Tests subproject is its own compilation unit. -->
  <ItemGroup>
    <Compile Remove="Tests/**" />
    <None Remove="Tests/**" />
    <InternalsVisibleTo Include="Tests" />
  </ItemGroup>

</Project>
